### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [truqu/elm-oauth2#20]
Hi, I have tried to use your google auth example from examples but I am getting: 

`Error: Problem with the flags given to your Elm program on initialization.

Json.Decode.oneOf failed in the following 2 ways:

(1) Problem with the given value:
    
    undefined
    
    Expecting null

(2) Problem with the given value:
    
    undefined
    
    Expecting a LIST`

Elm version: 0.19.1

**Comment by KtorZ** [comment]
Seems like a problem unrelated to the library but with some missing flags when initializing the elm application. 

```elm
main : Program (Maybe (List Int)) Model Msg
```

Looking at the examples, it seems that the actual `index.html` and the initialization code is not committed on the `master` branch :s .. but it is on the `gh-pages`:

https://github.com/truqu/elm-oauth2/blob/gh-pages/google/implicit/index.html

As you can see, the examples expect either undefined or a list of bytes to be given as an argument:

```js
    const app = Elm.Main.init({
        node: document.getElementById("app"),
        flags: rememberedBytes()
    });
```

I am not sure why the `index.html` wasn't included, probably an oversight. Sorry!

**Comment by KtorZ** [comment]
Now [versioned on `master`](https://github.com/truqu/elm-oauth2/blob/750068ebbce844354c9da2b927ef1a3427dc5dfa/examples/index.html).

I've also added [some instructions](https://github.com/truqu/elm-oauth2/tree/master/examples#readme) about how to build and run the examples locally :+1:
