### ISSUE TITLE
Build failure due to it's dependency ivadzy/bbase64 1.1.1

### ISSUE THREAD

**Issue by 0-gravity** [truqu/elm-oauth2#22]
Build is failing with:
Dependency problem!
-- CORRUPT PACKAGE DATA --------------------------------------------------------

I downloaded the source code for ivadzy/bbase64 1.1.1 from:

    https://github.com/ivadzy/bbase64/zipball/1.1.1/

But it looks like the hash of the archive has changed since publication:        

  Expected: 5ffd9a4d21ec0e3ac0eab3ed07e7c97832b04b98
    Actual: fba597639f122a3e9eb5db876f73d191c2f0a6c7

This usually means that the package author moved the version tag, so report it  
to them and see if that is the issue. Folks on Elm slack can probably help as   
well.

**Comment by jaforcade** [comment]
Looks like they renamed the package... 

[https://package.elm-lang.org/packages/chelovek0v/bbase64/latest/](https://package.elm-lang.org/packages/chelovek0v/bbase64/latest/)

**Comment by 0-gravity** [comment]
Can the package be updated with renamed dependency and published?
Our Azure pipeline is failing

**Comment by KtorZ** [comment]
It's a public repository, pull requests are welcome :)

**Comment by KtorZ** [comment]
See: https://github.com/truqu/elm-oauth2/releases/tag/7.0.1
