### ISSUE TITLE
Add support for ID Token in token response for Authorization Code Flow with PKCE

### ISSUE THREAD

**Issue by charles-dexter-ward** [truqu/elm-oauth2#31]
According to

https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce

the token response data must (could?) contain an ID Token (id_token).

It seems to me that this is not actually supported in AuthenticationSuccess:

```
type alias AuthenticationSuccess =
    { token : Token
    , refreshToken : Maybe Token
    , expiresIn : Maybe Int
    , scope : List String
    }
```

**Comment by 0-gravity** [comment]
This issue is open for almost a year. Is there any progress?

**Comment by KtorZ** [comment]
- https://github.com/truqu/elm-oauth2/issues/7#issuecomment-364372665
- https://github.com/truqu/elm-oauth2/issues/21#issuecomment-635280646
