### ISSUE TITLE
Claims from id_token

### ISSUE THREAD

**Issue by razzeee** [truqu/elm-oauth2#7]
Would you be able to extract the claims from the id_token?
See specification here: https://auth0.com/docs/tokens/id-token

This might be of some help to decode, but doesn't seem to return claims at this stage. http://package.elm-lang.org/packages/ktonon/elm-jsonwebtoken/1.0.2/JsonWebToken

**Comment by KtorZ** [comment]
Well, `id_tokens` are out of scope here (no pun intended). This library is an implementation of the OAuth 2.0 protocol. Identity Tokens are part of the [OpenID & OpenID Connect](https://openid.net/connect/) protocols which are built on top of OAuth 2.0.

**Comment by razzeee** [comment]
Feared that you might say that. Thank you :)
