### ISSUE TITLE
Problems with instagram oauth2

### ISSUE THREAD

**Issue by mrkaspa** [truqu/elm-oauth2#8]
The url instagram returns does not have a token_type with bearer value it doesnot return this params, the url is this:

http://your-redirect-uri#access_token=ACCESS-TOKEN

**Comment by KtorZ** [comment]
Well, that's probably something to tell Instagram then :upside_down_face: 
This library _merely_ implements the [RFC-6749](https://tools.ietf.org/html/rfc6749#section-4.2.2) and I am (once again) sad to see big companies not following a standard that is that well written :/ 

As explained in [#3](https://github.com/truqu/elm-oauth2/pull/3#issuecomment-353081817), I am not really willing to alter the library to cope with faulty implementation of different services; I hope you understand why. I am happy to fix bugs (if any) and add abstractions that would make things easier without altering the original essence.

Having said that, you can probably work-around that by adding yourself this parameter to the URL before giving it to elm-oauth2 for parsing ?
