### ISSUE TITLE
Update truqu/elm-base64

### ISSUE THREAD

**Issue by razzeee** [truqu/elm-oauth2#9]
Can you please update `truqu/elm-base64`

I'm using this package and want to use elm-jwt which also uses elm-base64 but in a newer version. So they clash and I can't install it to my elm-package.json

"truqu/elm-base64": "2.0.0 <= v < 3.0.0"

https://github.com/simonh1000/elm-jwt/blob/5.3.0/elm-package.json

**Comment by KtorZ** [comment]
Done :+1: 

http://package.elm-lang.org/packages/truqu/elm-oauth2/2.2.1

( PRs are _truly_ welcome for that kind of stuff :smile:  ! )

**Comment by razzeee** [comment]
Sorry, didn't feel up to the task.
Libraries are still on my todo list with elm, but so far I don't really know where to start :)

But your changes seem quiet trivial.
